{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "mysql-credentials",
    "namespace": "default",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "mysql-credentials",
        "namespace": "default",
        "creationTimestamp": null
      },
      "type": "Opaque",
      "data": null
    },
    "encryptedData": {
      "connection": "AgA4S7ZGiVcHiQ8rfIomTCoWRE8iDpcu1zJtEhxHA2K/lLh/ij1XNvrUtvFJaWOnfKpNm6lPr9RC5AZrxtFgLV9YS0JF3tTOpFQRZ5+I5s93Fgh0jle9vXUY4JPID34CdUDQSG+3D0gJYeXUfOVGSPD+xrch4FYuehP9PkFeOgAZ/E6Htd2hIKBcUTSohnKMuSTKFbrSlMk6TrRDHEkYDA0DOkikxgnZI/89/lh7L1ZAIfUJUDejAgdMvvNQprDSrLIFrSOfSWcVrrcHzAr0zEFL0QFm5dFcXfLAe4wBn3pb5eK1jrjHNI4PGWXS2qtSHZU2ZGnlpm26eLX+Kjk8fo32tIPspb3rGqMdoKjLhY/d305VJMf+IYJiYOHACgdkXO7hwVacR8NXkb+QpHS736JQArtEKoNoV3koDL+1KrVfjdlvuUAj+eUIyjgUTJbIe4Gg6+IS1n6Z1xyK5MZc+OIb/JNMbYlGUUo2PDXVlSCvanTO8okg6t29dSNMvMV5Mqtyh0oC06VYnvSTDVisDbzEUAt53QqNHnav6acp9I7Thnf8AhPAujsTfMzzuJuhGbMJ+nEEGO9sqKusOjQ4cNtGAqbfaR+VBrB97vMJYINJaxAz0KFlcm7rA88UNCK5OuBx0VeAovTGuCKtzWs26dSbotPZ1mwZPynaBDpwhGiZFEStl0V3CV2W+bee3ZKIAwz5CuNy4f9KHJdZ/xe1HN4zKO5nAYog8yZW+zhZLgJkMH0=",
      "password": "AgAh926rhppZ6bGpxIADY5sGHahPG2/5jas9vLEhZ8jXHrLwXAQBmNQW/X5Eesz+DGaVbeo+AX0ukv0ZQlYCbwCI9bEhfFCXgj5ytjkXYAR1jxhGeWncyWz2EOXVFEDV7d8/Q06oVEbh7o/a4DNus+HN/mXcb8zQFAkfjmr4m0l4u4cG4X6ia5fHpcHCxdpyGZjXsoHZx2+jCAgylU4COiHPXBN+heYU6wGkN7hMPySkcQOmbP9wsP254+/F5XUCUL4OVWFsbsPpM8jPv4KIzYGb5AUHPilO5pDGANHyERJNpQplqSskr1cU/+Q+L6ePxWhADBpQj6YEHDD2Vti+/d6DkiHn8kxwdCHrDwJwus+u3ESFDMxd5n4Ked8qG8LyORp9xcB2MTFOZvMwib18znGWBScrR0BouVrtxJL/5xDVZLTNsTKu43oMMLilhnL771OzXEeAaQWtwtfe07GLDGrLqghV9rfdS5IMyBX7Ezb0yRLpCkruXVOKxgh1TDGMxRZWweKygesxx/VbdotII7j5nxFpOuxo9aRlb8jd9YHlWqCHZm4k8NTE3W4hThj3uYoTr21w77sypZOyRisw9q1IPtCj+HfWd9lvwz5DNjl07lfO675luxzCtoaY4f8W8VE6Zo2QaTtCByy2H5x5UJT6K0mNvKUQHo9DWPhq8DRvDChoHawsGK1vB3E73eplHQ5W/Py6Cc1eI1hjfyM57gY=",
      "username": "AgCBwb3ULA5ABOgqrFrkIBECeBGpzXNhSwnkWrR6GfRiIyijoucrYEIJS4oXAUhArtxcHK+HfI4yUNeSct33BqOsjFg3zLvyHEZmX+xuE5K6tixKtM+7/13mMEWU24w7ZonJRclrdpMbejlr8qx/6WHpIVKi65uepCIEmFkbOMAn2SX60nVkl8pNFUo4D00z8NENIRJ+NT4GS7EG6i8waG1qxcRjJyTjNh+L+jecRLwSL3LbqyK7y2JCzZWjvyxEQmsXnUlA9U1/4uSaPQkiBxKZ4IcZ2Hjdum5IDIHwe/o0MojSpDqazHpzEvEOr/qeDH28VOUxYc3GPUOM5shcxWbQ2o2RGqBKl0kp5xW11kxqnMs49QHYJTuNqc2qRfUY8t53BfeeWEgqn7xy4T9wD5DYhR0XpHQUV+WWI/Ao4B4+QUWPiioc9Pd5sLyu2pC94/GOpjgLYexuPry0x2TXgHbz2bm+p/ZiUK09UdAIBoRJYW6tKiJ63JlIvoLCfUYArxHUohTTrGnIt5s1IrLJPUiuHH989lWgJM9GjZqg5HPlYbE+9cBIDX0gT7G4ah8xCCA8R7VHIgoKcZQwAVRWtklo8hILzY/kVOS0KkLTfoUjxU44y5EFOhxpZIHvq1NolLuGU0MnO7zkN2oQsRUukDa2xwgxbOZwe9e03+YJ6AfCxyzjETDBf8XxGUGruQ/O25bcn9PWtsy8RTRd/w=="
    }
  }
}