{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "paypal-cert",
    "namespace": "default",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "paypal-cert",
        "namespace": "default",
        "creationTimestamp": null
      },
      "type": "Opaque",
      "data": null
    },
    "encryptedData": {
      "paypal.crt": "AgCg2d6P4PRUmwKDGhye265Fa01OfhfDqMwarEI8Rld5N8QdQFcEQkxue/uv6WvXs7OGvMD9pECJ7hUhD6V0im3XV7zdityaWNufdEmhtHeJtitMiG4yfEpCLVnIiztKg2tg9tasYTBpyaKHCCyGL3+/fs3QHKdECrNCoPByTUQbLjiZyYFHxfBpbvbhDAqMNpBt+qodwJWXSKDawdT1zVX0JXVjycxJwmvdHTWl184Wh6BaYGrQHy4HQaZNRMqI1EuFzx4xadty43zn0T1nAQfCw5M+wZlsIMDjTeh/HT06uLfUOQeJu3FneZiPkS55t5Lm1N/EGyZ1+AoQs5LNZI++11IPs5aMrGNKjl7MLfhzRTy7F8FWJSKbe/i5HJG8kTEe39OCNyh5FaYAWWgzTyQKEOMTypbcNDZ3TPzAFb5zFbV5zA/jGtnWzLvxZAf1MmTYincxFq1Ef1lx5CnS0MkVivaf3jHaCpgWb7JzU7d2Mli668FHxOU3f+ezfQWa9S07Mv+u39ZuHOU6VLCuQ1pkNaTtfKpnsiRJXlYbpon7UgLDJ9H2dmckWj8YKhPsAl0EIueuUAI9V/BpJmJ1YkzwYP2CTmCS/kaXf/EDaaV8PY2MA8wWGwEdZTPjFkQMpq+5wjAC8JQEFTFxATb4Qm2yL7NJQxqmABmI8MV1f6hbYvErKE9PisJA6ERjXZuOg36e8n1aKT4Ara0OMtSSKDvsQmSqrY5mcgWc3TEqYoy/nJgjcz2LvsVykSnhtOGm5WhIaYhSJJ+dqBU23lUKqKR/NJYXDVHbZRDO5j5d85IS3nhJpxFYw55WXwjey91HwxXEFOtRuTzkBb5O1LNPudtDVxplaPQSp8OziTF2xNOuTHIPPBTvKJTxjgQkL1mS9hukvQntaLdRkNvqDb9xDUDvVGaoNfQ858g0LCY2lVrQ23fAR9kDVyvXA+I7OjAU5yoZjEr/U9Q8dNgC6Dx9aBjfMPxQtgaHg/Pl+a8gggqkfLtSXuCy/0ZAccStdWrylH/okpMxCGlTxQAPYlkbSXlkpSMDbn9Yfvbf/dMpfQ5lZq6zt6tnWkn3fXlAMPQtC9ejLv0zEbaon8PQyLWE8v1BVCuslL8vOsI5cjBnvMKTDLeI/dGx4wPA0UQNuMP6JKYwblYwWgLGzoCI0Ru5xOKgdDTA1ZijepVbDidmNz22XKn3WQ5uTT6tvPcUzoWm2AuTQmwIL7aBMkEN/AF3uSjI9A8Kk5jptKk9wGE7bANA58byWwtrPfJi07LD0CFxIQTiFHIxEzWARKPHfCQZb0d2Um1hqEWhgQjJY42ufUvAHXVxUMkOvijDl5o2sHKV4kDPS/7xswDf9TCSFoR1yuaWQn6maoTxMBZWlva3MM2wxlWSJn/o/8Tew+Ad9VBKF0urxQVYm0g8BetAlBXf9rxl2oaD3GHxxIYMeeNYnhLp3W52io7ObJ9alhwRcr4ZyIwXkU1/kOGhYpcaQeVpeSm7qjJyQUCCjf/BeHgyEb3GESIUqtXC0p88zgzKoVovgmDp561eqVi283c/35+30YrIQ8bdr1ZAceh+v/tSGTzq/+fngscFfNjugz5BWPoXR3T1ZOO/6TE0XpDqXitJkKbdCpoSaNVSYxZb2095521Y5asQQUhUhqgBbCz08IFSeQz3JJVh5fR58aqiCM9yvydFmdz/6AQTpPvyKJFZlMLJJn9CLCmIJbru8xPDYVY8GWe4O9FWYAV12lC6CfNVIb3pjaTDlJyQG2bstPOG1315U4kP9qoP9IX/jH5N+yLZX8atP0kQnjMHa+wfbBp/Zpx2ffdOGkXGhjGJfXJS3h1a+4kdCyEzrYpKPBCMWWe7We3PjF9FjwANJz7WLuJSAgGb26FPFHiIFoRwaBcsm7jSMaqzm3XIhHkjkW0/MW6ZvDxPBmVfw+v8HiXEx2CSSdZ+PFGKOYJqVaacaeduhBGxgW4i1VCY1FcOFvYPBns/8ILtN6ek8EA3YVuSppsdT99dLT2CcpcU5QdH1dQPHaQf1kyY2hKeIJvkr8qxmp+4vf6AMrEz73ABYun2mgFakDFPhlnjpScb3SZEnNtB4Q4FiJ2n"
    }
  }
}